services:
  postgres:
    image: postgres:15
    container_name: ledgertec-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ledgertec
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ledgertec

  backend:
    build: ./backend
    container_name: ledgertec-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/ledgertec
      FRONT_URL: http://localhost:5173
      PORT: 3001
    ports:
      - "3001:3001"
    command: sh -c "npx prisma migrate deploy && npm start"
    networks:
      - ledgertec

  frontend:
    build: ./frontend
    container_name: ledgertec-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "5173:5173"
    networks:
      - ledgertec

volumes:
  pgdata:

networks:
  ledgertec:
